# Generated by Django 5.2.1 on 2025-05-25 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseTwoDayInLife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narrative', models.JSONField(default=dict)),
                ('career_path', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='day_in_life', to='api.careertrack')),
            ],
        ),
        migrations.CreateModel(
            name='PhaseTwoFunFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('fact_text', models.TextField()),
                ('takeaway', models.TextField()),
                ('career_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fun_facts', to='api.careertrack')),
            ],
        ),
        migrations.CreateModel(
            name='PhaseTwoReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_1', models.CharField(max_length=200)),
                ('option_2', models.CharField(max_length=200)),
                ('option_3', models.CharField(max_length=200)),
                ('career_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to='api.careertrack')),
            ],
        ),
        migrations.CreateModel(
            name='PhaseTwoScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_a', models.CharField(max_length=200)),
                ('option_b', models.CharField(max_length=200)),
                ('option_c', models.CharField(max_length=200)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('explanation', models.TextField()),
                ('career_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='api.careertrack')),
            ],
        ),
    ]
